import type { Metadata } from "next";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
import DefaultLayout from "./DefaultLayout/DefaulLayout";

export const metadata: Metadata = {
  title: "DC TOOL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <DefaultLayout>
         <div >{children}</div>
        </DefaultLayout>
      </body>
    </html>
  );
}
